# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

inherit git-r3 systemd

DESCRIPTION="Privacy-respecting metasearch engine aggregating 280+ search services"
HOMEPAGE="https://docs.searxng.org/ https://github.com/searxng/searxng"
EGIT_REPO_URI="https://github.com/searxng/searxng.git"

LICENSE="AGPL-3+"
SLOT="0"
KEYWORDS="~amd64"
IUSE="+valkey"
RESTRICT="network-sandbox"

S="${WORKDIR}/${P}"

RDEPEND="
	acct-group/searxng
	acct-user/searxng
	dev-libs/libxml2
	dev-libs/libxslt
	www-servers/uwsgi[python]
	valkey? ( dev-db/valkey )
"
BDEPEND="
	${RDEPEND}
	dev-vcs/git
"

SEARXNG_HOME="/usr/lib/searxng"

src_unpack() {
	git-r3_src_unpack
}

src_prepare() {
	default

	# Generate version file so it doesn't need git at runtime
	cat > searx/version_frozen.py <<-EOF
	# SPDX-License-Identifier: AGPL-3.0-or-later
	# generated by Gentoo ebuild
	VERSION_STRING = "2026.07.04+gentoo"
	VERSION_TAG = "2026.07.04+gentoo"
	DOCKER_TAG = "2026.07.04-gentoo"
	GIT_URL = "https://github.com/searxng/searxng.git"
	GIT_BRANCH = "master"
	EOF

	# Relax version pins for portaged Python deps
	sed -i 's/==/>=/g' requirements.txt || die
}

src_compile() {
	python3 -m venv "${T}/searxng-pyenv" || die
	source "${T}/searxng-pyenv/bin/activate" || die

	pip install --upgrade pip setuptools wheel pyyaml msgspec \
		typing-extensions pybind11 || die

	pip install --use-pep517 --no-build-isolation -e "${S}" || die

	deactivate
}

src_install() {
	local SEARXNG_PYENV="${SEARXNG_HOME}/searx-pyenv"
	local DEST="${D}${SEARXNG_PYENV}"

	# Copy the full virtualenv preserving structure & permissions
	mkdir -p "${DEST}" || die
	cp -a "${T}/searxng-pyenv/." "${DEST}/" || die

	# Replace python/pip symlinks with system references
	rm -f "${DEST}/bin/python" "${DEST}/bin/python3" "${DEST}/bin/pip3" || true
	ln -s /usr/bin/python3 "${DEST}/bin/python"
	ln -s /usr/bin/python3.14 "${DEST}/bin/python3"
	ln -s python3 "${DEST}/bin/python3.14"
	ln -s pip "${DEST}/bin/pip3"

	# Fix venv config to point at the deployed location
	cat > "${DEST}/pyvenv.cfg" <<-CFGEOF
	home = /usr/bin
	include-system-site-packages = false
	version = 3.14.6
	executable = /usr/bin/python3.14
	CFGEOF

	# CLI symlink
	dosym "${SEARXNG_PYENV}/bin/searxng-run" /usr/bin/searxng-run

	# Source code (templates, static files, etc.)
	insinto "${SEARXNG_HOME}/searxng-src"
	doins -r "${S}/searx"
	doins "${S}/setup.py"
	doins "${S}/README.rst"
	doins "${S}/LICENSE"

	# Config
	insinto /etc/searxng
	doins "${FILESDIR}/settings.yml"

	# uwsgi config
	insinto /etc/uwsgi/apps-available
	doins "${FILESDIR}/searxng.ini"
	dosym ../../../../etc/uwsgi/apps-available/searxng.ini /etc/uwsgi/apps-enabled/searxng.ini

	insinto /etc/uwsgi
	doins "${FILESDIR}/searxng.ini"

	# Systemd
	systemd_dounit "${FILESDIR}/searxng.service"

	# Runtime dirs
	keepdir /var/log/searxng
	keepdir "${SEARXNG_HOME}/run"
	keepdir /var/lib/searxng

	fowners searxng:searxng /var/log/searxng
	fowners searxng:searxng "${SEARXNG_HOME}/run"
	fowners searxng:searxng /var/lib/searxng
	fperms 755 /var/log/searxng
	fperms 755 "${SEARXNG_HOME}/run"
	fperms 755 /var/lib/searxng

	dodoc README.rst
}

pkg_postinst() {
	einfo ""
	einfo "SearXNG ${PV} installed."
	einfo ""
	einfo "Quick start:"
	einfo "  1. Edit /etc/searxng/settings.yml"
	einfo "     - Set a secret_key (or use SEARXNG_SECRET env var)"
	einfo ""
	if use valkey; then
		einfo "  2. Start Valkey:  rc-service valkey start"
		einfo "  3. Enable Valkey: rc-update add valkey default"
		einfo "  4. Uncomment valkey.url in /etc/searxng/settings.yml"
		einfo ""
	fi
	einfo "  systemctl start searxng"
	einfo "  systemctl enable searxng"
	einfo ""
	einfo "Default: http://127.0.0.1:8888"
	einfo "Reverse proxy (nginx/apache) recommended for external access."
	einfo "Docs: https://docs.searxng.org/"
	einfo ""
}
